name: 'Run Godel Command'
description: 'Runs a godel command'
inputs:
  go-version:
    description: 'Go version to use'
    required: true
  godel-command:
    description: 'Godel command'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    - uses: actions/cache@v2
      with:
        path: |
          ~/.godel
        key: ${{ runner.os }}-godel-${{ hashFiles('godelw', 'godel/config/godel.yml') }}
    - run: ./godelw ${{ inputs.godel-command }}
