name: actions

on: push

jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      #####################
      # START Go dist setup
      #####################
      - id: set-gopath
        run: echo "::set-output name=GOPATH::$(go env GOPATH)"
      - id: go-dist-info
        uses: ./.github/actions/go-dist-info
        with:
          gopath: ${{ steps.set-gopath.outputs.gopath }}
      - id: restore-go-dist-from-cache
        if: steps.go-dist-info.outputs.go-dist-exists != 'true'
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.set-gopath.outputs.gopath }}/go-dists/${{ steps.go-dist-info.outputs.go-dist-version }}
          key: ${{ steps.go-dist-info.outputs.go-dist-version }}
      - id: go-dist-setup
        uses: ./.github/actions/go-dist-setup
        with:
          gopath: ${{ steps.set-gopath.outputs.gopath }}
          go-version: ${{ steps.go-dist-info.outputs.go-dist-version }}
      #####################
      # END Go dist setup
      #####################
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.godel
          key: ${{ runner.os }}-godel-${{ hashFiles('godelw', 'godel/config/godel.yml') }}
      - run: ./godelw verify --apply=false --skip-test

  test:
    strategy:
      matrix:
        go-version: [go1.15.12, go1.16.5]
        os: [ubuntu-20.04, macos-10.15]
        include:
          - os: ubuntu-20.04
            os-arch: linux-amd64
          - os: macos-10.15
            os-arch: darwin-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ matrix.os-arch }}
      #####################
      # START Go dist setup
      #####################
      - id: set-gopath
        run: echo "::set-output name=GOPATH::$(go env GOPATH)"
      - id: go-dist-info
        uses: ./.github/actions/go-dist-info
        with:
          go-version: ${{ matrix.go-version }}
          gopath: ${{ steps.set-gopath.outputs.gopath }}
      - id: restore-go-dist-from-cache
        if: steps.go-dist-info.outputs.go-dist-exists != 'true'
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.set-gopath.outputs.gopath }}/go-dists/${{ steps.go-dist-info.outputs.go-dist-version }}
          key: ${{ steps.go-dist-info.outputs.go-dist-version }}
      - id: go-dist-setup
        uses: ./.github/actions/go-dist-setup
        with:
          gopath: ${{ steps.set-gopath.outputs.gopath }}
          go-version: ${{ steps.go-dist-info.outputs.go-dist-version }}
      #####################
      # END Go dist setup
      #####################
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.godel
          key: ${{ runner.os }}-godel-${{ hashFiles('godelw', 'godel/config/godel.yml') }}
      - name: Test
        run: ./godelw test
